### PR TITLE
Add find by one tag feature

### PR DESCRIPTION
**Pull request by SimHanKiong**

### CODE REVIEW

**Review by ziyang27 — APPROVED** [review]
Neat and clean code 👍 LGTM!

**Comment by tanyunchao** [comment]
LGTM!

nit: 
it is not immediately clear to me (person without context) whats the diff btw `FindTag` and `FindTagOr` from just the name of the command itself. Could consider renaming.

could consider adding a simple summary on ur PR giving context to the PR itself to let reviewers have an idea of what to look out for. Title helps but I think as the PRs get more complex, having context would greatly aid the reviewers in their effectiveness as well.

**Comment by ziyang27** [comment]
> LGTM!
> 
> nit: it is not immediately clear to me (person without context) whats the diff btw `FindTag` and `FindTagOr` from just the name of the command itself. Could consider renaming.
> 
> could consider adding a simple summary on ur PR giving context to the PR itself to let reviewers have an idea of what to look out for. Title helps but I think as the PRs get more complex, having context would greatly aid the reviewers in their effectiveness as well.

Excellent nits

**Comment by SimHanKiong** [comment]
Deleted the redundant find by 1 tag feature, please merge after looking through, thank you

**Pull request merged**
