### PR TITLE
Add profile panel in Ui

### PR DESCRIPTION
**Pull request by ziyang27**
- pushing to check code coverage
- edited multiple files, also added fxml files which cannot be tested, will find a way
- likely to fail some tests

### CODE REVIEW

**Comment by tanyunchao** [comment]
@ziyang27 is this still an open issue or can this be closed?

**Comment by ziyang27** [comment]
@tanyunchao still need, dun have enough code coverage to merge yet

**Comment by ziyang27** [comment]
Some changes from my initial PR:
- added tests
- integrated with the rest of the features

Note: The test coverage will tank a little. I implemented quite a few UI components that were not tested.

**Comment by ziyang27** [comment]
@tanyunchao @Colex2000 ready to merge already, can help me a take a look when you free?

**Review by Colex2000 — COMMENTED** [review]
LGTM! Fantastic work

**Review by Colex2000 — APPROVED** [review]

**Pull request merged**
